### ISSUE TITLE
utcsmad.com domain no longer has departmental blessing

### ISSUE THREAD

**Issue by nickswalker** [utcsmad/MAD-site#22]
We aren't allowed to prefix ourselves with "UT" any more, so we should evaluate other domain options. Also, the current setup (iframe) breaks responsive CSS. It should be changed to a straight 301 redirect.

**Comment by nickswalker** [comment]
Bring in the domain owner: @jessetipton

**Comment by jessetipton** [comment]
I'll disable the forward :cry:

**Comment by nickswalker** [comment]
Lori emailed us with this info as the semester was starting. She said she would be able to reimburse for registering new domains and the such. I'm also noticing now that we're illicitly continuing to use the utcsmad Twitter handle. Calling @tomasro27 for next steps
